### ISSUE TITLE
Where we have to put data-config.xml

### ISSUE THREAD

**Issue by sheeraz308** [rohitbemax/dataimporthandler#29]
Hello,

In which folder we have to put data-config.xml file as we are not able to run this command:

[root@db07 solr2]# ./server/scripts/cloud-scripts/zkcli.sh -z localhost:9983 -cmd putfile "/configs/products.AUTOCREATED/data-config.xml" data-config.xml
INFO  - 2021-12-31 14:23:51.742; org.apache.solr.common.cloud.ConnectionManager; Waiting for client to connect to ZooKeeper
INFO  - 2021-12-31 14:23:51.765; org.apache.solr.common.cloud.ConnectionManager; zkClient has connected
INFO  - 2021-12-31 14:23:51.765; org.apache.solr.common.cloud.ConnectionManager; Client is connected to ZooKeeper
WARN  - 2021-12-31 14:23:51.770; org.apache.zookeeper.ClientCnxn; An exception was thrown while closing send thread for session 0x1004c97096d0009. => EndOfStreamException: Unable to read additional data from server sessionid 0x1004c97096d0009, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x1004c97096d0009, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275) ~[zookeeper-3.6.2.jar:3.6.2]
Exception in thread "main" java.io.FileNotFoundException: data-config.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.solr.cloud.ZkCLI.main(ZkCLI.java:310)

@rohitbemax Can you please help us to fix this issue.
Thanks in Advance.

**Comment by walecharohit** [comment]
is this resolved ?? @sheeraz308
