### ISSUE TITLE
current DataImportHandler not working with Solr 9

### ISSUE THREAD

**Issue by zniff** [rohitbemax/dataimporthandler#32]
Hi everbody
I just tried to run Solr 9.0.0 with the latest dataimporthandler (yeah, I know it is for Solr 8.10...) but it seems a lot of Solr core (and other) classes have changed their signatures etc. and it is not possible to start the DIH with Solr 9, e.g.:

```
16:00:00,751 [ERROR] org.apache.solr.core.CoreContainer - Error waiting for SolrCore to be loaded on startup
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [commoditiesi18n-0]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.solr.core.CoreContainer.lambda$load$11(CoreContainer.java:979)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:259)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.solr.common.SolrException: Unable to create core [commoditiesi18n-0]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1583)
	at org.apache.solr.core.CoreContainer.lambda$load$10(CoreContainer.java:950)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202)
	... 5 more
Caused by: org.apache.solr.common.SolrException: 'void org.apache.solr.metrics.SolrMetricsContext.gauge(org.apache.solr.core.SolrInfoBean, com.codahale.metrics.Gauge, boolean, java.lang.String, java.lang.String[])'
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1204)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1048)
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1560)
	... 7 more
Caused by: java.lang.NoSuchMethodError: 'void org.apache.solr.metrics.SolrMetricsContext.gauge(org.apache.solr.core.SolrInfoBean, com.codahale.metrics.Gauge, boolean, java.lang.String, java.lang.String[])'
	at org.apache.solr.handler.dataimport.DataImportHandler.initializeMetrics(DataImportHandler.java:306)
	at org.apache.solr.metrics.SolrCoreMetricManager.registerMetricProducer(SolrCoreMetricManager.java:139)
	at org.apache.solr.core.SolrCore.registerInfoBean(SolrCore.java:3425)
	at org.apache.solr.core.PluginBag.registerMBean(PluginBag.java:310)
	at org.apache.solr.core.PluginBag.put(PluginBag.java:227)
	at org.apache.solr.core.PluginBag.init(PluginBag.java:276)
	at org.apache.solr.core.RequestHandlers.initHandlersFromConfig(RequestHandlers.java:117)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1135)
	... 9 more
```

to (quick'n'dirty) test I went into `solr.handler.dataimport.DataImportHandler.java` and simply commented out the call to org.apache.solr.metrics.SolrMetricsContext.gauge(...) and rebuild the jar file just to run into the next issue:

```
16:17:47,499 [ERROR] org.apache.solr.core.CoreContainer - Error waiting for SolrCore to be loaded on startup
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [commoditiesi18n-0]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.solr.core.CoreContainer.lambda$load$11(CoreContainer.java:979)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:259)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.solr.common.SolrException: Unable to create core [commoditiesi18n-0]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1583)
	at org.apache.solr.core.CoreContainer.lambda$load$10(CoreContainer.java:950)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202)
	... 5 more
Caused by: org.apache.solr.common.SolrException: org/apache/lucene/analysis/util/ResourceLoader
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1204)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1048)
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1560)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoader
	at org.apache.solr.handler.dataimport.DataImportHandler.inform(DataImportHandler.java:111)
	at org.apache.solr.core.SolrResourceLoader.inform(SolrResourceLoader.java:722)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1155)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.ResourceLoader
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
	... 12 more

```

so the actual question (already put up [here](https://github.com/rohitbemax/dataimporthandler/issues/31) would be: is it planned to upgrade the DIH to support Solr 9...?

thanks and best regards
Erich

**Comment by kdebski85** [comment]
I can see that `org.apache.lucene.analysis.util.ResourceLoader` was moved to `org.apache.lucene.util.ResourceLoader`.

I think the first step to fix it would be to create `branch_9x` branch from `branch_8x`.

**Comment by epugh** [comment]
@kdebski85 That makes sense to me ;-).  @zniff in terms of a plan, well, this is an open source community, so the "plan" is generated by the community!  Maybe I should say, the proto-community that needs to form around DIH.

If someone contributes a patch to upgrade DIH to Solr 9, then I know I'd be happy to review it.

**Comment by zniff** [comment]
I see the problem :-)

**Comment by kdebski85** [comment]
I tried:
```
    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <solr-version>9.0.0</solr-version>
    </properties>
```
but it gave me about 10 compilation errors.

For example:
1.
```
      if (core == null) {
        configDir = SolrResourceLoader.locateSolrHome().toString();
      } else {
        configDir = core.getResourceLoader().getConfigDir();
      }
```
there is no longer `SolrResourceLoader.locateSolrHome()` method.

2.
```
      if(dataImporter != null && dataImporter.getCore() != null
          && dataImporter.getCore().getResourceLoader().getCoreProperties() != null){
        resolver =  new VariableResolver(dataImporter.getCore().getResourceLoader().getCoreProperties());
      } else {
        resolver = new VariableResolver();
      }
```
there is no getCoreProperties() method.

3.
```
password = CryptoKeys.decodeAES(initProps.getProperty("password"), new String(chars, 0, len)).trim();
```
there is no `CryptoKeys.decodeAES` method.

4.
DataImportHandler must implement `Name getPermissionName(AuthorizationContext request)`

5.
solrMetricsContext.gauge method signature changed

I think these changes cannot be easily implemented without in-depth knowledge of Solr.

**Comment by nightvixen** [comment]
This does not look any difficult, since there's not much changes.
Well, with few fixes I've managed to get it working, though I have not tried UI but it's likely to be missing, api seems to be working but few tests are failing. You can build it with mvn package  -Dmaven.test.skip=true
It's on my GitHub https://github.com/nightvixen/dataimporthandler/

I'll try to check if'd possible to find any solution for UI.

**Comment by kdebski85** [comment]
I also worked on the issue and pull request is ready:
https://github.com/rohitbemax/dataimporthandler/pull/33

This pull request has target branch `rohitbemax:branch_8x`. Please create `rohitbemax:branch_9x` from `rohitbemax:branch_8x`, so I can set proper target branch.

This pull request does not contain UI. I do not plan to work it.

All tests pass. I was not able to fix test `TestZKPropertiesWriter`. I was getting `"No registered leader was found after waiting for 30000ms"` so I ignored the test for now.

I also tested full/delta import on Solr 9.0.0. I had to first re-add DIH UI based on 8.11.1. Everything worked fine. The only issue I had was that my collections use a custom function which reads some external file. I had to set SOLR_SECURITY_MANAGER_ENABLED=false when starting Solr. Otherwise, my function could not access the file.

**Comment by trenshaw** [comment]
Hoping the pull request is approved soon. Need DIH on Solr 9.

**Comment by chatman** [comment]
Sorry about the delay, will do this over this weekend. Thank you for waiting.

**Comment by zniff** [comment]
...any news on this topic... :-)

**Comment by OkkeKlein** [comment]
@chatman Can you give us an update on the status? I would like to use DIH in Solr 9 as well.

**Comment by epugh** [comment]
This project would really benefit from someone taking ownership and working through PR's...   Maybe that person wants to fork it (again) and then work on getting all the PR's in?

**Comment by crewone** [comment]
Any news?

**Comment by OkkeKlein** [comment]
@chatman thank you for the Solr 9.0.0 release!

**Comment by zniff** [comment]
Thanks a lot! Works fine!

**Comment by zniff** [comment]
seems to be ok and closing... :-)
