### ISSUE TITLE
The manifest SHA512 doesn't match expected SHA512

### ISSUE THREAD

**Issue by sauntheninja2** [rohitbemax/dataimporthandler#83]
Following the steps from the github repo when I try to run this command

`bin/solr package deploy data-import-handler -y -collections products`

I get this error in command prompt (Note :- Running this on windows)

org.apache.solr.common.SolrException: org.apache.solr.common.SolrException: The manifest SHA512 doesn't match expected SHA512. Possible unauthorized manipulation. Expected: 9fec9f50ce5ec61cef27a0ade0656b1bdd00b409af296f8dcfdb5a357ad73cdc638848fe2f283282c36e3698f3838047982041f634c0f8607adbe7096fd7f603, calculated: a0903d7d9d0d123dec949e976d967c2dc6e350d7c8474ae98deb5277010056453a7d2a814c7841b75327b4fbc743ab932de8eab6bf59d2b21a6943d306f15087, manifest location: /package/data-import-handler/9.4.0/manifest.json
        at org.apache.solr.packagemanager.PackageManager.fetchInstalledPackageInstances(PackageManager.java:228)
        at org.apache.solr.packagemanager.PackageManager.getPackageInstance(PackageManager.java:880)
        at org.apache.solr.packagemanager.PackageManager.deploy(PackageManager.java:925)
        at org.apache.solr.cli.PackageTool.runImpl(PackageTool.java:184)
        at org.apache.solr.cli.ToolBase.runTool(ToolBase.java:52)
        at org.apache.solr.cli.SolrCLI.main(SolrCLI.java:227)
Caused by: org.apache.solr.common.SolrException: The manifest SHA512 doesn't match expected SHA512. Possible unauthorized manipulation. Expected: 9fec9f50ce5ec61cef27a0ade0656b1bdd00b409af296f8dcfdb5a357ad73cdc638848fe2f283282c36e3698f3838047982041f634c0f8607adbe7096fd7f603, calculated: a0903d7d9d0d123dec949e976d967c2dc6e350d7c8474ae98deb5277010056453a7d2a814c7841b75327b4fbc743ab932de8eab6bf59d2b21a6943d306f15087, manifest location: /package/data-import-handler/9.4.0/manifest.json
        at org.apache.solr.packagemanager.PackageUtils.fetchManifest(PackageUtils.java:216)
        at org.apache.solr.packagemanager.PackageManager.fetchInstalledPackageInstances(PackageManager.java:202)
        ... 5 more

ERROR: org.apache.solr.common.SolrException: The manifest SHA512 doesn't match expected SHA512. Possible unauthorized manipulation. Expected: 9fec9f50ce5ec61cef27a0ade0656b1bdd00b409af296f8dcfdb5a357ad73cdc638848fe2f283282c36e3698f3838047982041f634c0f8607adbe7096fd7f603, calculated: a0903d7d9d0d123dec949e976d967c2dc6e350d7c8474ae98deb5277010056453a7d2a814c7841b75327b4fbc743ab932de8eab6bf59d2b21a6943d306f15087, manifest location: /package/data-import-handler/9.4.0/manifest.json

**Comment by manoj1206** [comment]
I am facing the same issue. Did you find a fix for this?

**Comment by chrajesh** [comment]
I am not facing this issue at all
We were even started using data import handler  9.7.0 as well in my
application.

Thanks,
R.
+91 9948668111

**Comment by chrajesh** [comment]
Please check the sole version u installed and the data import handler which
u r using it

I am suspecting both are not in sync

Generally it is alway getting latest data import handler version

Thanks,
R.
+91 9948668111

**Comment by ruggiero-m** [comment]
I have the same error too

**Comment by Sara0009** [comment]
I have the same error.

I'm using Solr 9.7.0, so I attempted to install data-import-handler:9.7.0.

I'm really stuck here. Please help me.

**Comment by Sara0009** [comment]
Which is correct—the expected value or the calculated value?

ERROR: org.apache.solr.common.SolrException: The manifest SHA512 doesn't match expected SHA512. Possible unauthorized manipulation. Expected: 7946526df7546c7aa552772af5e27c3858a13e8a1048b912fb0a01ffa27781d41852c2f873d549d8734c3e99a73f950bd856829698ff0205acd22699a188925e, calculated: a9ab3a1d827622e243eb2b39a96934aaa85359770ba996a7026ac1b84013b18ee5f9a77cccb9148394c9cdf46fb6286e5ed92c35b7f902af73fa32e0277e30ba, manifest location: /package/data-import-handler/9.7.0/manifest.json

**Comment by tamerMarzouk** [comment]
I am facing the same issue:
with solr-9.7.0-slim running on OracleLinux 9.5 under WSL windows 11 
```
org.apache.solr.common.SolrException: org.apache.solr.common.SolrException: The manifest SHA512 doesn't match expected SHA512. Possible unauthorized manipulation. Expected: 7946526df7546c7aa552772af5e27c3858a13e8a1048b912fb0a01ffa27781d41852c2f873d549d8734c3e99a73f950bd856829698ff0205acd22699a188925e, calculated: a9ab3a1d827622e243eb2b39a96934aaa85359770ba996a7026ac1b84013b18ee5f9a77cccb9148394c9cdf46fb6286e5ed92c35b7f902af73fa32e0277e30ba, manifest location: /package/data-import-handler/9.7.0/manifest.json
        at org.apache.solr.packagemanager.PackageManager.fetchInstalledPackageInstances(PackageManager.java:228)
        at org.apache.solr.packagemanager.PackageManager.getPackageInstance(PackageManager.java:880)
        at org.apache.solr.packagemanager.PackageManager.deploy(PackageManager.java:925)
        at org.apache.solr.cli.PackageTool.runImpl(PackageTool.java:184)
        at org.apache.solr.cli.ToolBase.runTool(ToolBase.java:52)
        at org.apache.solr.cli.SolrCLI.main(SolrCLI.java:227)
Caused by: org.apache.solr.common.SolrException: The manifest SHA512 doesn't match expected SHA512. Possible unauthorized manipulation. Expected: 7946526df7546c7aa552772af5e27c3858a13e8a1048b912fb0a01ffa27781d41852c2f873d549d8734c3e99a73f950bd856829698ff0205acd22699a188925e, calculated: a9ab3a1d827622e243eb2b39a96934aaa85359770ba996a7026ac1b84013b18ee5f9a77cccb9148394c9cdf46fb6286e5ed92c35b7f902af73fa32e0277e30ba, manifest location: /package/data-import-handler/9.7.0/manifest.json
        at org.apache.solr.packagemanager.PackageUtils.fetchManifest(PackageUtils.java:216)
        at org.apache.solr.packagemanager.PackageManager.fetchInstalledPackageInstances(PackageManager.java:202)
        ... 5 more

ERROR: org.apache.solr.common.SolrException: The manifest SHA512 doesn't match expected SHA512. Possible unauthorized manipulation. Expected: 7946526df7546c7aa552772af5e27c3858a13e8a1048b912fb0a01ffa27781d41852c2f873d549d8734c3e99a73f950bd856829698ff0205acd22699a188925e, calculated: a9ab3a1d827622e243eb2b39a96934aaa85359770ba996a7026ac1b84013b18ee5f9a77cccb9148394c9cdf46fb6286e5ed92c35b7f902af73fa32e0277e30ba, manifest location: /package/data-import-handler/9.7.0/manifest.json
```

**Comment by lukres** [comment]
Something sketchy's going on, had the same problem, then reinstalled the same version and it worked

**Comment by lukres** [comment]
the difference between the failing and installing version is a weird byte appended to the end of manifest.json .. installs correctly after replacing manifest.json with the one that has this rubbish at the end

**Comment by ctassell** [comment]
> the difference between the failing and installing version is a weird byte appended to the end of manifest.json .. installs correctly after replacing manifest.json with the one that has this rubbish at the end

Where do we get the corrupted manifest.json that will actually work?
